[project]
name = "kp-gateway-selector"
version = "0.1.0"
description = "A library for dynamic payment gateway selection based on configurable rules."
authors = [
    {name = "KP team",email = "devs@kp.com"}
]
requires-python = ">=3.9"
dependencies = [
    "pydantic>=2.0",
    "SQLAlchemy>=1.4",
    "redis>=4.0",
    "cryptography>=3.0",
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0", "setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["kp_gateway_selector", "kp_gateway_selector.cache", "kp_gateway_selector.gateway_selector_v2", "kp_gateway_selector.postgresql", "kp_gateway_selector.utils"]
